site_name: Ultimate Starter Kit
site_url: https://hfjooste.github.io/UltimateStarterKit
repo_url: https://github.com/hfjooste/UltimateStarterKit
repo_name: hfjooste/UltimateStarterKit
remote_branch: docs
remote_name: git@github.com:hfjooste/UltimateStarterKit.git
extra_css: [styles.css]
plugins:
  - with-pdf:
      author: Henry Jooste
      cover: true
      cover_title: Ultimate Starter Kit
      cover_subtitle: Documentation
extra:
  social:
    - name: Sponsor Development
      icon: fontawesome/solid/heart
      link: https://github.com/sponsors/hfjooste
    - name: Linktree
      icon: fontawesome/solid/link
      link: https://linktr.ee/hfjooste
    - name: Mastodon
      icon: fontawesome/brands/mastodon
      link: https://mastodon.gamedev.place/@hfjooste
    - name: Reddit
      icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/HenryJooste
    - name: Twitter
      icon: fontawesome/brands/x-twitter
      link: https://twitter.com/hfjooste
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/hfjooste
    - name: Email
      icon: fontawesome/solid/envelope
      link: mailto:henryjooste95@gmail.com
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
nav:
  - Getting Started: index.md
  - Special Thanks: specialthanks.md
  - Console Codenames: platform_copyright.md
  - Core Functionality:
    - Input Devices: inputdevice.md
    - Game Instance: gameinstance.md
  - Logging System:
    - Logger: logger.md
    - Log Configuration: logconfig.md
  - Dialogue System:
    - Overview: dialogueoverview.md
    - Dialogue: dialogue.md
    - Participant: dialogueparticipant.md
    - Entry: dialogueentry.md
    - Transition:
      - Transition Type: dialoguetransitiontype.md
      - Transition Data: dialoguetransition.md
    - Manager: dialoguemanager.md
    - Widget: dialoguewidget.md
  - Inventory:
    - Inventory Component: inventorycomponent.md
    - Inventory Data: inventorydata.md
    - Inventory Item: inventoryitem.md
    - Inventory Item Data: inventoryitemdata.md
    - Inventory Menu Item: inventorymenuitem.md
    - Inventory Size: inventorysize.md
    - Inventory Widget: inventorywidget.md
  - Trackable Data:
    - Overview: trackabledataoverview.md
    - Data: trackabledata.md
    - Component: trackabledatacomponent.md
  - Audio:
    - Audio Overview: audio.md
    - Audio Utils: audioutils.md
    - Music Player: music.md
  - Characters:
    - Overview: platformer.md
    - Base Character: uskcharacter.md
    - FPS Character: fpscharacter.md
    - 3D Platformer Character: platformercharacter.md
    - Animation Instance: characteranimationinstance.md
    - Shadow Decal: platformershadow.md
  - Weapons:
    - Weapon: weapon.md
    - Weapon Type: weapontype.md
    - Weapon Fire Mode: weaponfiremode.md
    - Weapon Item: weaponitem.md
    - Weapon Ammo Item: weaponammoitem.md
    - Weapon Projectile: weaponprojectile.md
    - Weapon Projectile Data: weaponprojectiledata.md
    - Weapon Projectile Hit Data: weaponprojectilehitdata.md
    - Weapon Projectile Decal: weaponprojectiledecal.md
    - Weapon Utils: weaponutils.md
  - Items:
    - Allowed Collector: allowedcollector.md
    - Collectable Item: collectableitem.md
  - Interact System:
    - Interact Trigger: interacttrigger.md
    - Interact Widget: interactwidget.md
  - Quest System:
    - Quest: quest.md
    - Quest Component: questcomponent.md
    - Quest Manager: questmanager.md
    - Quest Widget: questwidget.md
  - UI & Widgets:
    - Collectable Item Icon: collectableitemicon.md
    - Credits:
      - Credits Entry: creditsentry.md
      - Credits Widget: creditswidget.md
    - FPS Counter: fpscounter.md
    - Input Indicator: inputindicator.md
    - Input Indicator Icon: inputindicatoricon.md
    - Menu: menu.md
    - Menu Item:
      - Navigation: menunavigation.md
      - Value Update Method: menuitemvalueupdatemethod.md
      - Menu Item Widget: menuitem.md
  - Settings:
    - Data: settingsdata.md
    - Config: settingsconfig.md
    - Items:
      - Types: settingsitemtype.md
      - Logic: settingsitem.md
    - Utils: settingsutils.md
  - Utils:
    - Config Utils: configutils.md
    - Platform:
      - Platform Type: platformtype.md
      - Platform Utils: platformutils.md
    - Project Utils: projectutils.md